# Generated by Django 4.2.2 on 2023-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Solutions architect'), (2, 'Engineer')], null=True),
        ),
    ]
